### PR TITLE
Add experimental Rails / ActiveRecord 5.0

### LINKED ISSUE #57: Support Rails / ActiveRecord 5.0
Hey @hzamani wanted to see if there are any plans to upgrade to Rails 5

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    active_record-acts_as was resolved to 1.0.0, which depends on
      activerecord (~> 4.1.2)

    rails (< 5.1, >= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
      activerecord (= 5.0.0.beta1)
```

### PR DESCRIPTION
**Pull request by jorgeaguirre**
Add scoped experimental support to `activerecord 5.0.0.beta1`. So does not add any modifications if it's used `activerecord ~>4`.
This can close #57 for now.
Also, add a new version to test in Travis to prove that the support `activerecord 5.0.0.beta1`.

### CODE REVIEW

**Comment by hzamani** [comment]
Thanks. But is thinks it's better to have different branches for each active-record major version, i.e. matching major version with active-record.

**Comment by yjukaku** [comment]
@hzamani Do you just want to update the gemspec file then? What version are you thinking of? 2.0.0 or 5.0.0 (to match ActiveRecord version)?

**Comment by hzamani** [comment]
I am a little busy these days. This will be merged with some modification some time in the next week, following rails versioning.

**Comment by shaneog** [comment]
Since Rails 5 is now released, do you think that you might have some time (no pressure) to look at this @hzamani ?
Thanks!

**Comment by manuelmeurer** [comment]
Implemented in #80

**Pull request closed without merging**
